# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 主页
    url: /
    weight: 10
  - name: 新闻动态
    url: post
    weight: 20
  - name: 研究团队 
    url: people
    weight: 30
  - name: 学术论文
    url: publication
    weight: 40
  - name: 研究简介
    url: research
    weight: 50
  - name: 科研项目
    url: funding
    weight: 60
  - name: 招生指南
    url: recruit
    weight: 70
